# Generated by Django 6.0.4 on 2026-04-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(default='Kenya Power', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_installation', models.DateField()),
                ('contractor_company', models.CharField(max_length=200)),
                ('contractor_rep', models.CharField(max_length=100)),
                ('icta_rep', models.CharField(blank=True, max_length=100)),
                ('indoor_ap1_serial', models.CharField(max_length=50)),
                ('indoor_ap1_location', models.CharField(max_length=100)),
                ('indoor_ap2_serial', models.CharField(blank=True, max_length=50)),
                ('indoor_ap2_location', models.CharField(blank=True, max_length=100)),
                ('indoor_ap3_serial', models.CharField(blank=True, max_length=50)),
                ('indoor_ap3_location', models.CharField(blank=True, max_length=100)),
                ('outdoor_ap_serial', models.CharField(max_length=50)),
                ('outdoor_ap_location', models.CharField(max_length=100)),
                ('onu_serial', models.CharField(max_length=50)),
                ('onu_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='reports.dcc')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'Before Installation'), ('after', 'After Installation')], max_length=10)),
                ('device_type', models.CharField(choices=[('ONU', 'ONU'), ('AP1', 'Indoor AP1'), ('AP2', 'Indoor AP2'), ('AP3', 'Indoor AP3'), ('OUT', 'Outdoor AP1')], default='ONU', max_length=3)),
                ('image', models.ImageField(upload_to='installation_photos/')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.institution')),
            ],
            options={
                'unique_together': {('institution', 'photo_type', 'device_type')},
            },
        ),
    ]
