# Generated by Django 6.0.4 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcc',
            name='project_name',
            field=models.CharField(default='DHS', max_length=100),
        ),
    ]
