# Generated by Django 6.0.4 on 2026-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dcc_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='project_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Project No.'),
        ),
    ]
