# Generated by Django 6.0.4 on 2026-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_institution_project_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='project_no',
            field=models.CharField(blank=True, default='01', max_length=50, verbose_name='Project No.'),
        ),
    ]
